version: '3.9'

services:
    postgres:
      container_name: slip-postgres-container
      image: postgres:17.0
      restart: always
      env_file:
      - .docker.env
      ports:
        - "5432:5432"
      volumes:
        - ./data/postgresql:/var/lib/postgresql/data
        - ./scripts/create_db.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - postgres

    pgadmin:
      container_name: slip-pgadmin-container
      image: dpage/pgadmin4:7.1
      restart: always
      env_file:
        - .docker.env
      ports:
        - "5050:80"
      depends_on:
        - postgres
      volumes:
        - pgadmin-data:/var/lib/pgadmin
      networks:
        - postgres

volumes:
  postgres:
    driver: local
  pgadmin-data:
    driver: local

networks:
  postgres:
    driver: bridge